spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:hsqldb:file:data/store;shutdown=true
logging:
  level:
    root: WARN
    me.belakede.thesis: INFO
    org.springframework: WARN
server:
  port: 8080
heartbeat:
  delay: 15000
  period: 3000