
spring:
  application:
    name: chat-server
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:chatdb
    platform: HSQL
  jpa:
    database-platform: HSQL
    show-sql: false
    hibernate:
      ddl-auto: update