
spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:file:~/.authdb;shutdown=true
    platform: HSQL
  jpa:
    database-platform: HSQL
    show-sql: false
    hibernate:
      ddl-auto: update

oauth2:
  client:
    id: c48dfe30-f50e
    secret: ef26cafe-557d-41d2-aec6-ff4a44c8871e

suspect:
  server:
    admin:
      username: admin
      password: password
