
spring:
  application:
    name: note-server
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:file:~/.notedb;shutdown=true
    platform: HSQL
  jpa:
    database-platform: HSQL
    show-sql: false
    hibernate:
      ddl-auto: update

